[project]
name = "responder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "python-dotenv>=1.1.1",
    "ruff>=0.13.0",
    "spond>=1.1.1",
]
