[project]
name = "padelbot"
version = "0.1.0"
description = "An app to simplify the life of managing the Equinor BIL Trondheim padel group"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "async-lru>=2.0.5",
    "configparser>=7.2.0",
    "python-dotenv>=1.1.1",
    "spond>=1.1.1",
    "types-aiofiles>=24.1.0.20250822",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
